import type { ProviderViewState, SettingsViewState, UsageViewState } from '../lib/types';

export const codexState: ProviderViewState = {
  source: 'live',
  refreshing: false,
  stale: false,
  error: null,
  errorKind: null,
  lastAttemptAt: null,
  snapshot: {
    providerId: 'codex',
    plan: 'Plus',
    refreshedAt: '2026-07-10T10:00:00Z',
    warnings: [],
    quotas: [
      {
        id: 'session',
        label: 'Session',
        usedPercent: 32,
        resetsAt: '2099-01-01T00:00:00Z',
        periodSeconds: 18000,
        format: 'percent',
        usedValue: null,
        limitValue: null,
      },
      {
        id: 'weekly',
        label: 'Weekly',
        usedPercent: 59,
        resetsAt: '2099-01-07T00:00:00Z',
        periodSeconds: 604800,
        format: 'percent',
        usedValue: null,
        limitValue: null,
      },
    ],
    valueMetrics: [
      {
        id: 'rateLimitResets',
        label: 'Rate Limit Resets',
        values: [{ number: 2, kind: 'count', label: 'available' }],
        expiriesAt: ['2099-01-02T00:00:00Z', '2099-01-03T00:00:00Z'],
      },
      {
        id: 'credits',
        label: 'Extra Usage',
        values: [
          { number: 32.84, kind: 'dollars' },
          { number: 821, kind: 'count', label: 'credits' },
        ],
        expiriesAt: [],
      },
    ],
    usage: {
      today: {
        tokens: 2100000,
        estimatedCostUsd: 3.84,
        costEstimated: true,
        estimateComplete: true,
      },
      yesterday: {
        tokens: 684000,
        estimatedCostUsd: 1.27,
        costEstimated: true,
        estimateComplete: true,
      },
      last30Days: {
        tokens: 3000000,
        estimatedCostUsd: 5.11,
        costEstimated: true,
        estimateComplete: true,
      },
      daily: [
        { date: '2026-07-10', tokens: 2100000, estimatedCostUsd: 3.84, estimateComplete: true },
      ],
      unknownModels: [],
    },
  },
};

export const liveState: UsageViewState = { providers: { codex: codexState } };

export const claudeState: ProviderViewState = {
  source: 'live',
  refreshing: false,
  stale: false,
  error: null,
  errorKind: null,
  lastAttemptAt: null,
  snapshot: {
    providerId: 'claude',
    plan: 'Max',
    refreshedAt: '2026-07-11T10:00:00Z',
    warnings: [],
    quotas: [
      {
        id: 'session',
        label: 'Session',
        usedPercent: 20,
        resetsAt: '2099-01-01T00:00:00Z',
        periodSeconds: 18000,
        format: 'percent',
        usedValue: null,
        limitValue: null,
      },
      {
        id: 'extra',
        label: 'Extra Usage',
        usedPercent: 25,
        resetsAt: null,
        periodSeconds: 0,
        format: 'dollars',
        usedValue: 12.5,
        limitValue: 50,
      },
    ],
    valueMetrics: [],
    usage: { today: null, yesterday: null, last30Days: null, daily: [], unknownModels: [] },
  },
};

export const antigravityState: ProviderViewState = {
  source: 'live',
  refreshing: false,
  stale: false,
  error: null,
  errorKind: null,
  lastAttemptAt: null,
  snapshot: {
    providerId: 'antigravity',
    plan: 'Pro',
    refreshedAt: '2026-07-11T10:00:00Z',
    warnings: [],
    quotas: [
      {
        id: 'geminiPro',
        label: 'Session',
        usedPercent: 0,
        resetsAt: '2099-01-01T00:00:00Z',
        periodSeconds: 18000,
        format: 'percent',
        usedValue: null,
        limitValue: null,
      },
      {
        id: 'geminiWeekly',
        label: 'Weekly',
        usedPercent: 13,
        resetsAt: '2099-01-07T00:00:00Z',
        periodSeconds: 604800,
        format: 'percent',
        usedValue: null,
        limitValue: null,
      },
    ],
    valueMetrics: [],
    usage: { today: null, yesterday: null, last30Days: null, daily: [], unknownModels: [] },
  },
};

export const settingsState: SettingsViewState = {
  notificationPermission: 'prompt',
  integrationError: null,
  standaloneWindow: false,
  platformSummary: null,
  settings: {
    schemaVersion: 4,
    knownProviderIds: ['claude', 'codex', 'antigravity'],
    showTotalSpend: true,
    theme: 'system',
    density: 'default',
    menuBarStyle: 'text',
    usageDisplay: 'left',
    resetDisplay: 'countdown',
    timeFormat: 'system',
    alwaysShowPacing: false,
    launchAtLogin: false,
    autoCheckUpdates: true,
    dismissedUpdateVersion: null,
    lastUpdateCheckAt: null,
    globalShortcut: null,
    notifications: { almostOut: false, cuttingItClose: false, willRunOut: false },
    totalSpendMetric: 'cost',
    totalSpendPeriod: 'today',
    detectionNoticeDismissed: true,
    providers: [
      {
        id: 'codex',
        enabled: true,
        detected: true,
        expanded: false,
        metrics: [
          { id: 'codex.session', enabled: true, section: 'alwaysVisible', pinned: true },
          { id: 'codex.weekly', enabled: true, section: 'alwaysVisible', pinned: true },
          { id: 'codex.spark', enabled: true, section: 'onDemand', pinned: false },
          { id: 'codex.sparkWeekly', enabled: true, section: 'onDemand', pinned: false },
          { id: 'codex.trend', enabled: true, section: 'alwaysVisible', pinned: false },
          { id: 'codex.credits', enabled: true, section: 'onDemand', pinned: false },
          { id: 'codex.rateLimitResets', enabled: true, section: 'onDemand', pinned: false },
          { id: 'codex.today', enabled: true, section: 'onDemand', pinned: false },
          { id: 'codex.yesterday', enabled: true, section: 'onDemand', pinned: false },
          { id: 'codex.last30', enabled: true, section: 'onDemand', pinned: false },
        ],
      },
    ],
  },
};
